version: '3'
services:
    mysql:
        container_name: challenge-mysql-container
        image: mysql:5.7

        environment:
            MYSQL_ROOT_PASSWORD: rootpass
            MYSQL_DATABASE: ${DB_NAME}
            MYSQL_USER: ${DB_USER}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        ports:
            - "${MYSQL_PORT}:3306"

    mysql-test:
        container_name: challenge-mysql-test-container
        image: mysql:5.7

        environment:
            MYSQL_ROOT_PASSWORD: rootpass
            MYSQL_DATABASE: ${DB_NAME}
            MYSQL_USER: ${DB_USER}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        ports:
            - "${MYSQL_TEST_PORT}:3306"

    node:
        container_name: challenge-node-container
        build:
            context: ../
            dockerfile: docker/images/node/Dockerfile

        ports:
            - "${APP_PORT}:1337"

        depends_on:
            - mysql

        volumes:
            - ../source:/home/app

        environment:
            - NODE_ENV=development
            - DB_NAME=${DB_NAME}
            - DB_HOST=${DB_HOST}
            - DB_USER=${DB_USER}
            - DB_PASSWORD=${DB_PASSWORD}
